pipeline {
  agent any
  environment {
        SLACK_WEBHOOK_URL = credentials("web-alerts-webhook-url")
    }
  parameters {
    string(
      name: 'cypressImage',
      description: 'The Docker image to use for cypress',
      defaultValue: params.testcafeImage ?: 'cypress/included:8.3.1'
    )
    string(
      name: 'BRANCH',
      description: 'The branch to run the tests from',
      defaultValue: params.BRANCH ?: 'master'
    )
    string(
      name: 'HOST',
      description: 'The url to run the tests on',
      defaultValue: params.TEST_URL ?: 'https://staging.formlabs.com'
    )
    string(
      name: 'browsers',
      description: 'Target browsers to run the tests in',
      defaultValue: params.browsers ?: 'chrome'
    )
  }

  stages {
    stage('Check out repo') {
      steps {
        checkout scm
      }
    }
    stage('Get credential files') {
      steps {
          withCredentials([file(credentialsId: 'jenkins-formlabs-e2e-test-gmail-credentials', variable: 'credentials'),
                        file(credentialsId: 'jenkins-formlabs-e2e-test-gmail-token', variable: 'gmail_token')]) {
            writeFile file: 'e2e-cypress/cypress/plugins/credentials.json', text: readFile(credentials)
            writeFile file: 'e2e-cypress/cypress/plugins/gmail_token.json', text: readFile(gmail_token)
        }
      }
    }   
    stage('Run e2e tests') {
      steps {
        script {
          docker.image(params.cypressImage).inside("--env CYPRESS_HOST=${params.HOST} --network host --entrypoint='' --user root") {
            sh "cd e2e-cypress && npm ci && cypress run --quiet --browser ${params.browsers} || exit 0 "
            sh "cd e2e-cypress && npm run generateHtml && mv mochawesome-report mochareports && npx cypress-slack-reporter --ci-provider jenkins --custom-url=https://jenkins.production.formlabs.cloud/job/formlabs/job/formlabs.com-e2e-testing-with-cypress/${env.BUILD_NUMBER}/Cypress_20HTML_20Reports/ --custom-text='<https://jenkins.production.formlabs.cloud/blue/organizations/jenkins/formlabs%2Fformlabs.com-e2e-testing-with-cypress/detail/formlabs.com-e2e-testing-with-cypress/${env.BUILD_NUMBER}/artifacts/|:camera_with_flash: *Review Diff Snapshots*>' && rm -r cypress/screenshots"
          }
        }
      }
    }
  }

  post {
    always {
      catchError {
        archiveArtifacts artifacts: '**/*.diff.png', fingerprint: true, allowEmptyArchive: true
        junit 'e2e-cypress/cypress/results/*.xml'
      }
      publishHTML target : [
        allowMissing: false,
        alwaysLinkToLastBuild: true,
        keepAll: true,
        reportDir: 'e2e-cypress/mochareports',
        reportFiles: 'mochawesome.html',
        reportName: 'Cypress HTML Reports',
        reportTitles: 'The Report']
    }
    cleanup {
      deleteDir()
    }
  }
}